spring.application.name=Event_Ticketing-Back_End
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/event_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.hikari.maximum-pool-size=10

#JPA Configurations
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop


# Stripe (add your test keys later)
stripe.api.key=sk_test_...
stripe.webhook.secret=whsec_...

# Mail (Gmail example ? use app password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your.email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Token Data
jwt.expiration=864000000
jwt.secret=mySecret1234mySecret1234mySecret1234mySecret1234mySecret1234mySecret1234mySecret1234

spring.jackson.deserialization.fail-on-null-for-primitives=false
#Using generated security password: 48e13a7a-95d7-47ae-aa5a-58b18216e724
